language: java

before_install: 

  # install necessary x32-libs for Android SDK 

  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++6:i386 lib32z1

  # download the latest android sdk and unzip 

  - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
  - tar -zxf android-sdk_r22.3-linux.tgz

  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

  # only update the sdk for the tools and platform-tools and required api level
  # (run "android list sdk --extended" to get the full list)
  
  - android list sdk --extended
  - echo "y" | android update sdk --filter tools,platform-tools,android-19 --no-ui --force
  - echo "y" | android update sdk -u -a -t 6
